version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

      - restore_cache:
          key: ng-planning-poker-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --legacy-peer-deps
      - save_cache:
          key: ng-planning-poker-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test:ci
